### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by Sean-Der** [webrtc-for-the-curious/webrtc-for-the-curious#86]
My goal is to have the book complete by Summer. At that time I am going to look at finding a publisher or self publishing. The goals is to put a physical copy in peoples hands. These are all the things that need to happen before then.

### What is the goal of the book, are we meeting that goal? *YES/NO*
The goal of the book is to to teach developers how to learn about WebRTC. The topic is too large for one book to describe fully. The book aims to introduce all the concepts need for developers to go learn on their own. We then should recommend books that focus on the single topic. The book also will not describe any WebRTC software in particular. This brings down the amount of developers that will read it. If we only focus on one WebRTC software it will miss its full potential. 

### Do the chapters cover all the high level concepts.
* [ ] What is WebRTC. A bundling of existing protocols, how they work together (chapter 1)
* [ ] Why does WebRTC need signaling, how does it work (chapter 2)
* [ ] Why does WebRTC need ICE, how does it work (chapter 3)
* [ ] Why does WebRTC need security, how does it work (chapter 4)
* [ ] Network Fundamental, precursor to Media/Data Transport (chapter 5)
* [ ] Why does WebRTC need RTP, how does it work (Chapter 6)
* [ ] Why does WebRTC need SCTP, how does it work (Chapter 7)
* [ ] What can you build with WebRTC (Chapter 8)
* [ ] Debugging WebRTC, tools and thinking like a WebRTC dev (chapter 9)
* [ ] History of WebRTC, how WebRTC is a bundling of existing protocols (chapter 10)
* [ ] FAQ, common questions redirects people to existing chapters (chapter 11)

### Is Chapter 1 Complete?
Yes, needs review.

### Is Chapter 2 Complete?
No
* [ ] Simulcast
* [ ] Transceiver Matching
* [ ] Renegotation

### Is Chapter 3 Complete?
No
* [ ] ICE isn't fully documented

### Is Chapter 4 Complete?
Yes, needs review. 

I would also like to recommend [Serious Cryptography: A Practical Introduction to Modern Encryption](https://www.amazon.com/Serious-Cryptography-Practical-Introduction-Encryption/dp/1593278268/) for users who wish to learn more.

### Is Chapter 5 Complete?
Hasn't even been started
* [ ] Media and Data is sent over UDP
* [ ] This is needed for NAT Traversal, but also allows us to do congestion control/error handling ourselves
* [ ] Congestion Control Primer
* [ ] Error Correction Primer (SACK, NACK, FEC)

### Is Chapter 6 Complete?
No, it needs extensive refactoring to fit with chapter 5. Outline here

### Is Chapter 7 Complete?
No, it needs extensive refactoring to fit with chapter 5. Outline here

### Is Chapter 8 Complete?
No needs extensive work/outline here

### Is Chapter 9 Complete?
No needs extensive work/outline here

### Is Chapter 10 Complete?
We still need an interviewee for
* [ ] ICE, STUN TURN
* [ ] SCTP
* [ ] DTLS/SRTP
* [ ] SCTP

### Is Chapter 11 Complete?
No needs extensive work/outline here

### Publishing
I would like to publish and let the publisher keep more/proceeds go to charity. It is more important to me that the book stays open and gets in as many hands as possible. 

* `No Starch Press` said they want something more applied. 
* `Pragmatic Bookshelf ` liked the book, but was apprehensive about the idea of it being open. Asked to come back when complete.
* `Packt Publishing` haven't approached yet. 
* I would like to send an email to fabien sanglard and ask his advice/opinions.
*
